import type { SimpleIcon } from "simple-icons";
import {
  siApachesolr,
  siC,
  siCplusplus,
  siCss,
  siDocker,
  siElasticsearch,
  siExpress,
  siFastapi,
  siGit,
  siGithub,
  siGooglebigtable,
  siGooglecloud,
  siGooglecloudspanner,
  siGooglecloudstorage,
  siGooglepubsub,
  siGrafana,
  siHtml5,
  siJavascript,
  siJest,
  siKubernetes,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siOpenjdk,
  siOpenapiinitiative,
  siPython,
  siReact,
  siSelenium,
  siSpringboot,
  siSwagger,
  siTailwindcss,
  siTemporal,
  siTypescript,
} from "simple-icons";

/** Portfolio item label → Simple Icons brand */
export const techItemBrandIcons: Record<string, SimpleIcon> = {
  C: siC,
  "C++": siCplusplus,
  Python: siPython,
  Java: siOpenjdk,
  JavaScript: siJavascript,
  TypeScript: siTypescript,
  HTML: siHtml5,
  CSS: siCss,
  "Spring Boot": siSpringboot,
  FastAPI: siFastapi,
  "Node.js": siNodedotjs,
  Express: siExpress,
  "RESTful APIs": siOpenapiinitiative,
  Swagger: siSwagger,
  "React.js": siReact,
  "Next.js": siNextdotjs,
  "Tailwind CSS": siTailwindcss,
  GCP: siGooglecloud,
  "Cloud Spanner": siGooglecloudspanner,
  Bigtable: siGooglebigtable,
  "Pub/Sub": siGooglepubsub,
  "Cloud Storage": siGooglecloudstorage,
  "Transcoder API": siGooglecloud,
  Elasticsearch: siElasticsearch,
  Solr: siApachesolr,
  MySQL: siMysql,
  MongoDB: siMongodb,
  Docker: siDocker,
  Kubernetes: siKubernetes,
  Temporal: siTemporal,
  Grafana: siGrafana,
  Git: siGit,
  GitHub: siGithub,
  Selenium: siSelenium,
  "Unit testing": siJest,
  Workers: siGooglecloud,
  "Cron jobs": siGooglecloud,
  "Cron Jobs": siGooglecloud,
};

const techItemAliases: Record<string, string> = {
  "Apache Solr": "Solr",
};

export function getTechItemBrandIcon(name: string) {
  const resolved = techItemAliases[name] ?? name;
  return techItemBrandIcons[resolved] ?? null;
}
